# Imports + Setup

In [74]:
import pandas as pd
import numpy as np
import plotly.express as px
from google.colab import files
import io

pd.set_option('display.max_rows', 4500)
pd.set_option('display.max_columns', 40)

In [75]:
uploaded = files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[filename]), sep=';')

Saving uci_success_dropout_data.csv to uci_success_dropout_data (3).csv

# Data Cleaning Initital Steps

In [76]:
#fix column naming
df.columns = [col.strip().lower().replace(' ', '_') for col in df.columns]
df = df.rename(columns={'daytime/evening_attendance\t': 'daytime_evening_attendance'})

In [77]:
#ensure age is greater than 0
df = df[df['age_at_enrollment'] > 0].copy()

#make dropout = 1 and graduate/enrolled = 0
df['target_binary'] = df['target'].apply(lambda x: 1 if x == 'Dropout' else 0)

#checking value amounts for target values
print(df['target_binary'].value_counts())
df.head()

target_binary
0    3003
1    1421
Name: count, dtype: int64

,marital_status,application_mode,application_order,course,daytime/evening_attendance,previous_qualification,previous_qualification_(grade),nacionality,mother's_qualification,father's_qualification,mother's_occupation,father's_occupation,admission_grade,displaced,educational_special_needs,debtor,tuition_fees_up_to_date,gender,scholarship_holder,age_at_enrollment,international,curricular_units_1st_sem_(credited),curricular_units_1st_sem_(enrolled),curricular_units_1st_sem_(evaluations),curricular_units_1st_sem_(approved),curricular_units_1st_sem_(grade),curricular_units_1st_sem_(without_evaluations),curricular_units_2nd_sem_(credited),curricular_units_2nd_sem_(enrolled),curricular_units_2nd_sem_(evaluations),curricular_units_2nd_sem_(approved),curricular_units_2nd_sem_(grade),curricular_units_2nd_sem_(without_evaluations),unemployment_rate,inflation_rate,gdp,target,target_binary
0,1,17,5,171,1,1,122.0,1,19,12,5,9,127.3,1,0,0,1,1,0,20,0,0,0,0,0,0.000000,0,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout,1
1,1,15,1,9254,1,1,160.0,1,1,3,3,3,142.5,1,0,0,0,1,0,19,0,0,6,6,6,14.000000,0,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate,0
2,1,1,5,9070,1,1,122.0,1,37,37,9,9,124.8,1,0,0,0,1,0,19,0,0,6,0,0,0.000000,0,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout,1
3,1,17,2,9773,1,1,122.0,1,38,37,5,3,119.6,1,0,0,1,0,0,20,0,0,6,8,6,13.428571,0,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate,0
4,2,39,1,8014,0,1,100.0,1,37,38,9,9,141.5,0,0,0,1,0,0,45,0,0,6,9,5,12.333333,0,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate,0

# Data Cleaning Continued From Changed Dataset
Analyzing next steps

In [78]:
#import cleaner dataset made from earlier changes

from google.colab import files
upload = files.upload()

cur_df = pd.read_csv('cleaned_student_data.csv')

Saving cleaned_student_data.csv to cleaned_student_data (2).csv

In [79]:
cur_df.head(5)

,marital_status,application_mode,application_order,course,daytime_evening_attendance,previous_qualification,previous_qualification_grade,nacionality,mothers_qualification,fathers_qualification,mothers_occupation,fathers_occupation,admission_grade,displaced,educational_special_needs,debtor,tuition_fees_up_to_date,gender,scholarship_holder,age_at_enrollment,international,curricular_units_1st_sem_credited,curricular_units_1st_sem_enrolled,curricular_units_1st_sem_evaluations,curricular_units_1st_sem_approved,curricular_units_1st_sem_grade,curricular_units_1st_sem_without_evaluations,curricular_units_2nd_sem_credited,curricular_units_2nd_sem_enrolled,curricular_units_2nd_sem_evaluations,curricular_units_2nd_sem_approved,curricular_units_2nd_sem_grade,curricular_units_2nd_sem_without_evaluations,unemployment_rate,inflation_rate,gdp,target
0,1,17,5,171,1,1,122.0,1,19,12,5,9,127.3,1,0,0,1,1,0,20,0,0,0,0,0,0.000000,0,0,0,0,0,0.000000,0,10.8,1.4,1.74,1
1,1,15,1,9254,1,1,160.0,1,1,3,3,3,142.5,1,0,0,0,1,0,19,0,0,6,6,6,14.000000,0,0,6,6,6,13.666667,0,13.9,-0.3,0.79,0
2,1,1,5,9070,1,1,122.0,1,37,37,9,9,124.8,1,0,0,0,1,0,19,0,0,6,0,0,0.000000,0,0,6,0,0,0.000000,0,10.8,1.4,1.74,1
3,1,17,2,9773,1,1,122.0,1,38,37,5,3,119.6,1,0,0,1,0,0,20,0,0,6,8,6,13.428571,0,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,0
4,2,39,1,8014,0,1,100.0,1,37,38,9,9,141.5,0,0,0,1,0,0,45,0,0,6,9,5,12.333333,0,0,6,6,6,13.000000,0,13.9,-0.3,0.79,0

In [80]:
#column overview

cur_df.columns

Index(['marital_status', 'application_mode', 'application_order', 'course',
       'daytime_evening_attendance', 'previous_qualification',
       'previous_qualification_grade', 'nacionality', 'mothers_qualification',
       'fathers_qualification', 'mothers_occupation', 'fathers_occupation',
       'admission_grade', 'displaced', 'educational_special_needs', 'debtor',
       'tuition_fees_up_to_date', 'gender', 'scholarship_holder',
       'age_at_enrollment', 'international',
       'curricular_units_1st_sem_credited',
       'curricular_units_1st_sem_enrolled',
       'curricular_units_1st_sem_evaluations',
       'curricular_units_1st_sem_approved', 'curricular_units_1st_sem_grade',
       'curricular_units_1st_sem_without_evaluations',
       'curricular_units_2nd_sem_credited',
       'curricular_units_2nd_sem_enrolled',
       'curricular_units_2nd_sem_evaluations',
       'curricular_units_2nd_sem_approved', 'curricular_units_2nd_sem_grade',
       'curricular_units_2nd_sem_without_evaluations', 'unemployment_rate',
       'inflation_rate', 'gdp', 'target'],
      dtype='object')

In [81]:
#seeing if any null values exist

cur_df.isnull().sum()

marital_status                                  0
application_mode                                0
application_order                               0
course                                          0
daytime_evening_attendance                      0
previous_qualification                          0
previous_qualification_grade                    0
nacionality                                     0
mothers_qualification                           0
fathers_qualification                           0
mothers_occupation                              0
fathers_occupation                              0
admission_grade                                 0
displaced                                       0
educational_special_needs                       0
debtor                                          0
tuition_fees_up_to_date                         0
gender                                          0
scholarship_holder                              0
age_at_enrollment                               0
international                                   0
curricular_units_1st_sem_credited               0
curricular_units_1st_sem_enrolled               0
curricular_units_1st_sem_evaluations            0
curricular_units_1st_sem_approved               0
curricular_units_1st_sem_grade                  0
curricular_units_1st_sem_without_evaluations    0
curricular_units_2nd_sem_credited               0
curricular_units_2nd_sem_enrolled               0
curricular_units_2nd_sem_evaluations            0
curricular_units_2nd_sem_approved               0
curricular_units_2nd_sem_grade                  0
curricular_units_2nd_sem_without_evaluations    0
unemployment_rate                               0
inflation_rate                                  0
gdp                                             0
target                                          0
dtype: int64

In [82]:
#ensuring only a total of two unique values for target exist
cur_df['target']
cur_df['target'].unique()

array([1, 0])

In [83]:
#ensuring correct data typing for each feature
cur_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 37 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   marital_status                                4424 non-null   int64
 1   application_mode                              4424 non-null   int64
 2   application_order                             4424 non-null   int64
 3   course                                        4424 non-null   int64
 4   daytime_evening_attendance                    4424 non-null   int64
 5   previous_qualification                        4424 non-null   int64
 6   previous_qualification_grade                  4424 non-null   float64
 7   nacionality                                   4424 non-null   int64
 8   mothers_qualification                         4424 non-null   int64
 9   fathers_qualification                         4424 non-null   int64
 10  mothers_occupation                            4424 non-null   int64
 11  fathers_occupation                            4424 non-null   int64
 12  admission_grade                               4424 non-null   float64
 13  displaced                                     4424 non-null   int64
 14  educational_special_needs                     4424 non-null   int64
 15  debtor                                        4424 non-null   int64
 16  tuition_fees_up_to_date                       4424 non-null   int64
 17  gender                                        4424 non-null   int64
 18  scholarship_holder                            4424 non-null   int64
 19  age_at_enrollment                             4424 non-null   int64
 20  international                                 4424 non-null   int64
 21  curricular_units_1st_sem_credited             4424 non-null   int64
 22  curricular_units_1st_sem_enrolled             4424 non-null   int64
 23  curricular_units_1st_sem_evaluations          4424 non-null   int64
 24  curricular_units_1st_sem_approved             4424 non-null   int64
 25  curricular_units_1st_sem_grade                4424 non-null   float64
 26  curricular_units_1st_sem_without_evaluations  4424 non-null   int64
 27  curricular_units_2nd_sem_credited             4424 non-null   int64
 28  curricular_units_2nd_sem_enrolled             4424 non-null   int64
 29  curricular_units_2nd_sem_evaluations          4424 non-null   int64
 30  curricular_units_2nd_sem_approved             4424 non-null   int64
 31  curricular_units_2nd_sem_grade                4424 non-null   float64
 32  curricular_units_2nd_sem_without_evaluations  4424 non-null   int64
 33  unemployment_rate                             4424 non-null   float64
 34  inflation_rate                                4424 non-null   float64
 35  gdp                                           4424 non-null   float64
 36  target                                        4424 non-null   int64
dtypes: float64(7), int64(30)
memory usage: 1.2 MB

In [84]:
#fixing misspelling
cur_df['nationality'] = cur_df['nacionality']
cur_df.drop('nacionality', axis=1, inplace=True)

In [85]:
cur_df.columns

Index(['marital_status', 'application_mode', 'application_order', 'course',
       'daytime_evening_attendance', 'previous_qualification',
       'previous_qualification_grade', 'mothers_qualification',
       'fathers_qualification', 'mothers_occupation', 'fathers_occupation',
       'admission_grade', 'displaced', 'educational_special_needs', 'debtor',
       'tuition_fees_up_to_date', 'gender', 'scholarship_holder',
       'age_at_enrollment', 'international',
       'curricular_units_1st_sem_credited',
       'curricular_units_1st_sem_enrolled',
       'curricular_units_1st_sem_evaluations',
       'curricular_units_1st_sem_approved', 'curricular_units_1st_sem_grade',
       'curricular_units_1st_sem_without_evaluations',
       'curricular_units_2nd_sem_credited',
       'curricular_units_2nd_sem_enrolled',
       'curricular_units_2nd_sem_evaluations',
       'curricular_units_2nd_sem_approved', 'curricular_units_2nd_sem_grade',
       'curricular_units_2nd_sem_without_evaluations', 'unemployment_rate',
       'inflation_rate', 'gdp', 'target', 'nationality'],
      dtype='object')

In [86]:
cur_df['nationality'].unique()

array([  1,  62,   6,  41,  26, 103,  13,  25,  21, 101,  11,  22,  32,
       100,  24, 109,   2, 108, 105,  14,  17])

In [87]:
cur_df.columns

Index(['marital_status', 'application_mode', 'application_order', 'course',
       'daytime_evening_attendance', 'previous_qualification',
       'previous_qualification_grade', 'mothers_qualification',
       'fathers_qualification', 'mothers_occupation', 'fathers_occupation',
       'admission_grade', 'displaced', 'educational_special_needs', 'debtor',
       'tuition_fees_up_to_date', 'gender', 'scholarship_holder',
       'age_at_enrollment', 'international',
       'curricular_units_1st_sem_credited',
       'curricular_units_1st_sem_enrolled',
       'curricular_units_1st_sem_evaluations',
       'curricular_units_1st_sem_approved', 'curricular_units_1st_sem_grade',
       'curricular_units_1st_sem_without_evaluations',
       'curricular_units_2nd_sem_credited',
       'curricular_units_2nd_sem_enrolled',
       'curricular_units_2nd_sem_evaluations',
       'curricular_units_2nd_sem_approved', 'curricular_units_2nd_sem_grade',
       'curricular_units_2nd_sem_without_evaluations', 'unemployment_rate',
       'inflation_rate', 'gdp', 'target', 'nationality'],
      dtype='object')

To Do:
- look into simplifying Parents Occupation and their Qualifications
- Value 99 is blank for both Parents Occupations
- Drop any features that risk data leakage

In [88]:
#simplify/replace parents occupation

def simplify_occupation(x):
    if x in [1, 2, 122, 123, 125]:
        return "Highly Skilled"
    elif x in [3, 7, 131]:
        return "Skilled"
    elif x in [4, 5, 141, 143]:
        return "Administrative"
    elif x in [9, 191, 192, 193]:
        return "Unskilled"
    elif x in [10, 101, 102, 103]:
        return "Military"
    else:
        return "Other"

cur_df['mothers_occupation'] = cur_df['mothers_occupation'].apply(simplify_occupation)
cur_df['fathers_occupation'] = cur_df['fathers_occupation'].apply(simplify_occupation)

In [89]:
#simplify/replace parents qualifications

def simplify_education(x):
    if x in [35, 36]:
        return "No Education"
    elif x in [9, 10, 11, 26, 29]:
        return "Basic"
    elif x in [1, 12, 14, 19]:
        return "Secondary"
    elif x in [2, 3, 4, 5, 40, 43, 44]:
        return "Higher"
    else:
        return "Other"

cur_df['mothers_qualification'] = cur_df['mothers_qualification'].apply(simplify_education)
cur_df['fathers_qualification'] = cur_df['fathers_qualification'].apply(simplify_education)

current courses:

33 - Biofuel Production Technologies (DONE)

171 - Animation and Multimedia Design  (DONE)

8014 - Social Service (evening attendance)    (DONE)

9003 - Agronomy   (DONE)

9070 - Communication Design

9085 - Veterinary Nursing

9119 - Informatics Engineering

9130 - Equinculture

9147 - Management

9238 - Social Service

9254 - Tourism

9500 - Nursing

9556 - Oral Hygiene

9670 - Advertising and Marketing Management

9773 - Journalism and Communication

9853 - Basic Education

9991 - Management (evening attendance)

In [90]:
#simplify courses feature

def simplify_courses(x):
    if x in [33]:
        return "Engineering/Technology"
    elif x in [9119]:
        return "Computer Science/IT"
    elif x in [9003, 9130]:
        return "Agriculture/Animal Sciences"
    elif x in [9085, 9500, 9556]:
        return "Health"
    elif x in [9147, 9991]:
        return "Business/Management"
    elif x in [9254, 9670]:
        return "Business/Services"
    elif x in [8014, 9238]:
        return "Social Services"
    elif x in [9853]:
        return "Education"
    elif x in [171, 9070]:
        return "Design/Creative"
    elif x in [9773]:
        return "Media/Communication"
    else:
        return "Other"

cur_df['course'] = cur_df['course'].apply(simplify_courses)

In [91]:
#One Hot Encode Parents qualifications + occupations + courses

cols_to_encode = [
    'mothers_occupation',
    'fathers_occupation',
    'mothers_qualification',
    'fathers_qualification',
    'course'
]

cur_df = pd.get_dummies(cur_df, columns=cols_to_encode, drop_first=True)

In [92]:
cur_df.head(5)

,marital_status,application_mode,application_order,daytime_evening_attendance,previous_qualification,previous_qualification_grade,admission_grade,displaced,educational_special_needs,debtor,tuition_fees_up_to_date,gender,scholarship_holder,age_at_enrollment,international,curricular_units_1st_sem_credited,curricular_units_1st_sem_enrolled,curricular_units_1st_sem_evaluations,curricular_units_1st_sem_approved,curricular_units_1st_sem_grade,...,fathers_occupation_Other,fathers_occupation_Skilled,fathers_occupation_Unskilled,mothers_qualification_Higher,mothers_qualification_No Education,mothers_qualification_Other,mothers_qualification_Secondary,fathers_qualification_Higher,fathers_qualification_No Education,fathers_qualification_Other,fathers_qualification_Secondary,course_Business/Management,course_Business/Services,course_Computer Science/IT,course_Design/Creative,course_Education,course_Engineering/Technology,course_Health,course_Media/Communication,course_Social Services
0,1,17,5,1,1,122.0,127.3,1,0,0,1,1,0,20,0,0,0,0,0,0.000000,...,False,False,True,False,False,False,True,False,False,False,True,False,False,False,True,False,False,False,False,False
1,1,15,1,1,1,160.0,142.5,1,0,0,0,1,0,19,0,0,6,6,6,14.000000,...,False,True,False,False,False,False,True,True,False,False,False,False,True,False,False,False,False,False,False,False
2,1,1,5,1,1,122.0,124.8,1,0,0,0,1,0,19,0,0,6,0,0,0.000000,...,False,False,True,False,False,True,False,False,False,True,False,False,False,False,True,False,False,False,False,False
3,1,17,2,1,1,122.0,119.6,1,0,0,1,0,0,20,0,0,6,8,6,13.428571,...,False,True,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,True,False
4,2,39,1,0,1,100.0,141.5,0,0,0,1,0,0,45,0,0,6,9,5,12.333333,...,False,False,True,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,True

In [93]:
cur_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 59 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   marital_status                                4424 non-null   int64
 1   application_mode                              4424 non-null   int64
 2   application_order                             4424 non-null   int64
 3   daytime_evening_attendance                    4424 non-null   int64
 4   previous_qualification                        4424 non-null   int64
 5   previous_qualification_grade                  4424 non-null   float64
 6   admission_grade                               4424 non-null   float64
 7   displaced                                     4424 non-null   int64
 8   educational_special_needs                     4424 non-null   int64
 9   debtor                                        4424 non-null   int64
 10  tuition_fees_up_to_date                       4424 non-null   int64
 11  gender                                        4424 non-null   int64
 12  scholarship_holder                            4424 non-null   int64
 13  age_at_enrollment                             4424 non-null   int64
 14  international                                 4424 non-null   int64
 15  curricular_units_1st_sem_credited             4424 non-null   int64
 16  curricular_units_1st_sem_enrolled             4424 non-null   int64
 17  curricular_units_1st_sem_evaluations          4424 non-null   int64
 18  curricular_units_1st_sem_approved             4424 non-null   int64
 19  curricular_units_1st_sem_grade                4424 non-null   float64
 20  curricular_units_1st_sem_without_evaluations  4424 non-null   int64
 21  curricular_units_2nd_sem_credited             4424 non-null   int64
 22  curricular_units_2nd_sem_enrolled             4424 non-null   int64
 23  curricular_units_2nd_sem_evaluations          4424 non-null   int64
 24  curricular_units_2nd_sem_approved             4424 non-null   int64
 25  curricular_units_2nd_sem_grade                4424 non-null   float64
 26  curricular_units_2nd_sem_without_evaluations  4424 non-null   int64
 27  unemployment_rate                             4424 non-null   float64
 28  inflation_rate                                4424 non-null   float64
 29  gdp                                           4424 non-null   float64
 30  target                                        4424 non-null   int64
 31  nationality                                   4424 non-null   int64
 32  mothers_occupation_Highly Skilled             4424 non-null   bool
 33  mothers_occupation_Military                   4424 non-null   bool
 34  mothers_occupation_Other                      4424 non-null   bool
 35  mothers_occupation_Skilled                    4424 non-null   bool
 36  mothers_occupation_Unskilled                  4424 non-null   bool
 37  fathers_occupation_Highly Skilled             4424 non-null   bool
 38  fathers_occupation_Military                   4424 non-null   bool
 39  fathers_occupation_Other                      4424 non-null   bool
 40  fathers_occupation_Skilled                    4424 non-null   bool
 41  fathers_occupation_Unskilled                  4424 non-null   bool
 42  mothers_qualification_Higher                  4424 non-null   bool
 43  mothers_qualification_No Education            4424 non-null   bool
 44  mothers_qualification_Other                   4424 non-null   bool
 45  mothers_qualification_Secondary               4424 non-null   bool
 46  fathers_qualification_Higher                  4424 non-null   bool
 47  fathers_qualification_No Education            4424 non-null   bool
 48  fathers_qualification_Other                   4424 non-null   bool
 49  fathers_qualification_Secondary               4424 non-null   bool
 50  course_Business/Management                    4424 non-null   bool
 51  course_Business/Services                      4424 non-null   bool
 52  course_Computer Science/IT                    4424 non-null   bool
 53  course_Design/Creative                        4424 non-null   bool
 54  course_Education                              4424 non-null   bool
 55  course_Engineering/Technology                 4424 non-null   bool
 56  course_Health                                 4424 non-null   bool
 57  course_Media/Communication                    4424 non-null   bool
 58  course_Social Services                        4424 non-null   bool
dtypes: bool(27), float64(7), int64(25)
memory usage: 1.2 MB

In [94]:
cur_df.columns

Index(['marital_status', 'application_mode', 'application_order',
       'daytime_evening_attendance', 'previous_qualification',
       'previous_qualification_grade', 'admission_grade', 'displaced',
       'educational_special_needs', 'debtor', 'tuition_fees_up_to_date',
       'gender', 'scholarship_holder', 'age_at_enrollment', 'international',
       'curricular_units_1st_sem_credited',
       'curricular_units_1st_sem_enrolled',
       'curricular_units_1st_sem_evaluations',
       'curricular_units_1st_sem_approved', 'curricular_units_1st_sem_grade',
       'curricular_units_1st_sem_without_evaluations',
       'curricular_units_2nd_sem_credited',
       'curricular_units_2nd_sem_enrolled',
       'curricular_units_2nd_sem_evaluations',
       'curricular_units_2nd_sem_approved', 'curricular_units_2nd_sem_grade',
       'curricular_units_2nd_sem_without_evaluations', 'unemployment_rate',
       'inflation_rate', 'gdp', 'target', 'nationality',
       'mothers_occupation_Highly Skilled', 'mothers_occupation_Military',
       'mothers_occupation_Other', 'mothers_occupation_Skilled',
       'mothers_occupation_Unskilled', 'fathers_occupation_Highly Skilled',
       'fathers_occupation_Military', 'fathers_occupation_Other',
       'fathers_occupation_Skilled', 'fathers_occupation_Unskilled',
       'mothers_qualification_Higher', 'mothers_qualification_No Education',
       'mothers_qualification_Other', 'mothers_qualification_Secondary',
       'fathers_qualification_Higher', 'fathers_qualification_No Education',
       'fathers_qualification_Other', 'fathers_qualification_Secondary',
       'course_Business/Management', 'course_Business/Services',
       'course_Computer Science/IT', 'course_Design/Creative',
       'course_Education', 'course_Engineering/Technology', 'course_Health',
       'course_Media/Communication', 'course_Social Services'],
      dtype='object')

To Do:
- Simplify Application_mode
- Investigate class imbalance and next steps

In [95]:
def simplify_application_mode(x):
    if x in [1, 17, 18]:
        return "Regular Admission"

    elif x in [42, 43, 51, 57]:
        return "Transfer/Change"

    elif x in [5, 16]:
        return "Special Entry"

    elif x in [7, 15, 39, 44, 53]:
        return "Non-Traditional"

    else:
        return "Other"

cur_df['application_mode'] = cur_df['application_mode'].apply(simplify_application_mode)
cur_df = pd.get_dummies(cur_df, columns=['application_mode'], drop_first=True)

In [96]:
cur_df.head(5)

,marital_status,application_order,daytime_evening_attendance,previous_qualification,previous_qualification_grade,admission_grade,displaced,educational_special_needs,debtor,tuition_fees_up_to_date,gender,scholarship_holder,age_at_enrollment,international,curricular_units_1st_sem_credited,curricular_units_1st_sem_enrolled,curricular_units_1st_sem_evaluations,curricular_units_1st_sem_approved,curricular_units_1st_sem_grade,curricular_units_1st_sem_without_evaluations,...,mothers_qualification_No Education,mothers_qualification_Other,mothers_qualification_Secondary,fathers_qualification_Higher,fathers_qualification_No Education,fathers_qualification_Other,fathers_qualification_Secondary,course_Business/Management,course_Business/Services,course_Computer Science/IT,course_Design/Creative,course_Education,course_Engineering/Technology,course_Health,course_Media/Communication,course_Social Services,application_mode_Other,application_mode_Regular Admission,application_mode_Special Entry,application_mode_Transfer/Change
0,1,5,1,1,122.0,127.3,1,0,0,1,1,0,20,0,0,0,0,0,0.000000,0,...,False,False,True,False,False,False,True,False,False,False,True,False,False,False,False,False,False,True,False,False
1,1,1,1,1,160.0,142.5,1,0,0,0,1,0,19,0,0,6,6,6,14.000000,0,...,False,False,True,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
2,1,5,1,1,122.0,124.8,1,0,0,0,1,0,19,0,0,6,0,0,0.000000,0,...,False,True,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True,False,False
3,1,2,1,1,122.0,119.6,1,0,0,1,0,0,20,0,0,6,8,6,13.428571,0,...,False,True,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,True,False,False
4,2,1,0,1,100.0,141.5,0,0,0,1,0,0,45,0,0,6,9,5,12.333333,0,...,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False

In [97]:
#ensure the one hot encoded features are 0s and 1s and not True/False

bool_cols = cur_df.select_dtypes(include='bool').columns
cur_df[bool_cols] = cur_df[bool_cols].astype(int)

To Do:

- Investigate possible class imbalance
- Update Data Dictionary based on parents qualifications/occupation changes + course/application mode changes

In [98]:
cur_df.head(10)

,marital_status,application_order,daytime_evening_attendance,previous_qualification,previous_qualification_grade,admission_grade,displaced,educational_special_needs,debtor,tuition_fees_up_to_date,gender,scholarship_holder,age_at_enrollment,international,curricular_units_1st_sem_credited,curricular_units_1st_sem_enrolled,curricular_units_1st_sem_evaluations,curricular_units_1st_sem_approved,curricular_units_1st_sem_grade,curricular_units_1st_sem_without_evaluations,...,mothers_qualification_No Education,mothers_qualification_Other,mothers_qualification_Secondary,fathers_qualification_Higher,fathers_qualification_No Education,fathers_qualification_Other,fathers_qualification_Secondary,course_Business/Management,course_Business/Services,course_Computer Science/IT,course_Design/Creative,course_Education,course_Engineering/Technology,course_Health,course_Media/Communication,course_Social Services,application_mode_Other,application_mode_Regular Admission,application_mode_Special Entry,application_mode_Transfer/Change
0,1,5,1,1,122.0,127.3,1,0,0,1,1,0,20,0,0,0,0,0,0.000000,0,...,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0
1,1,1,1,1,160.0,142.5,1,0,0,0,1,0,19,0,0,6,6,6,14.000000,0,...,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
2,1,5,1,1,122.0,124.8,1,0,0,0,1,0,19,0,0,6,0,0,0.000000,0,...,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0
3,1,2,1,1,122.0,119.6,1,0,0,1,0,0,20,0,0,6,8,6,13.428571,0,...,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0
4,2,1,0,1,100.0,141.5,0,0,0,1,0,0,45,0,0,6,9,5,12.333333,0,...,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
5,2,1,0,19,133.1,114.8,0,0,1,1,1,0,50,0,0,5,10,5,11.857143,0,...,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0
6,1,1,1,1,142.0,128.4,1,0,0,1,0,1,18,0,0,7,9,7,13.300000,0,...,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0
7,1,4,1,1,119.0,113.1,1,0,0,0,1,0,22,0,0,5,5,0,0.000000,0,...,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0
8,1,3,1,1,137.0,129.3,0,0,0,1,0,1,21,1,0,6,8,6,13.875000,0,...,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0
9,1,1,1,1,138.0,123.0,1,0,1,0,0,0,18,0,0,6,9,5,11.400000,0,...,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0

In [99]:
cur_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 62 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   marital_status                                4424 non-null   int64
 1   application_order                             4424 non-null   int64
 2   daytime_evening_attendance                    4424 non-null   int64
 3   previous_qualification                        4424 non-null   int64
 4   previous_qualification_grade                  4424 non-null   float64
 5   admission_grade                               4424 non-null   float64
 6   displaced                                     4424 non-null   int64
 7   educational_special_needs                     4424 non-null   int64
 8   debtor                                        4424 non-null   int64
 9   tuition_fees_up_to_date                       4424 non-null   int64
 10  gender                                        4424 non-null   int64
 11  scholarship_holder                            4424 non-null   int64
 12  age_at_enrollment                             4424 non-null   int64
 13  international                                 4424 non-null   int64
 14  curricular_units_1st_sem_credited             4424 non-null   int64
 15  curricular_units_1st_sem_enrolled             4424 non-null   int64
 16  curricular_units_1st_sem_evaluations          4424 non-null   int64
 17  curricular_units_1st_sem_approved             4424 non-null   int64
 18  curricular_units_1st_sem_grade                4424 non-null   float64
 19  curricular_units_1st_sem_without_evaluations  4424 non-null   int64
 20  curricular_units_2nd_sem_credited             4424 non-null   int64
 21  curricular_units_2nd_sem_enrolled             4424 non-null   int64
 22  curricular_units_2nd_sem_evaluations          4424 non-null   int64
 23  curricular_units_2nd_sem_approved             4424 non-null   int64
 24  curricular_units_2nd_sem_grade                4424 non-null   float64
 25  curricular_units_2nd_sem_without_evaluations  4424 non-null   int64
 26  unemployment_rate                             4424 non-null   float64
 27  inflation_rate                                4424 non-null   float64
 28  gdp                                           4424 non-null   float64
 29  target                                        4424 non-null   int64
 30  nationality                                   4424 non-null   int64
 31  mothers_occupation_Highly Skilled             4424 non-null   int64
 32  mothers_occupation_Military                   4424 non-null   int64
 33  mothers_occupation_Other                      4424 non-null   int64
 34  mothers_occupation_Skilled                    4424 non-null   int64
 35  mothers_occupation_Unskilled                  4424 non-null   int64
 36  fathers_occupation_Highly Skilled             4424 non-null   int64
 37  fathers_occupation_Military                   4424 non-null   int64
 38  fathers_occupation_Other                      4424 non-null   int64
 39  fathers_occupation_Skilled                    4424 non-null   int64
 40  fathers_occupation_Unskilled                  4424 non-null   int64
 41  mothers_qualification_Higher                  4424 non-null   int64
 42  mothers_qualification_No Education            4424 non-null   int64
 43  mothers_qualification_Other                   4424 non-null   int64
 44  mothers_qualification_Secondary               4424 non-null   int64
 45  fathers_qualification_Higher                  4424 non-null   int64
 46  fathers_qualification_No Education            4424 non-null   int64
 47  fathers_qualification_Other                   4424 non-null   int64
 48  fathers_qualification_Secondary               4424 non-null   int64
 49  course_Business/Management                    4424 non-null   int64
 50  course_Business/Services                      4424 non-null   int64
 51  course_Computer Science/IT                    4424 non-null   int64
 52  course_Design/Creative                        4424 non-null   int64
 53  course_Education                              4424 non-null   int64
 54  course_Engineering/Technology                 4424 non-null   int64
 55  course_Health                                 4424 non-null   int64
 56  course_Media/Communication                    4424 non-null   int64
 57  course_Social Services                        4424 non-null   int64
 58  application_mode_Other                        4424 non-null   int64
 59  application_mode_Regular Admission            4424 non-null   int64
 60  application_mode_Special Entry                4424 non-null   int64
 61  application_mode_Transfer/Change              4424 non-null   int64
dtypes: float64(7), int64(55)
memory usage: 2.1 MB

In [101]:
#export cleaned dataset :)

cur_df.to_csv('final_student_data.csv', index=False)

In [102]:
#download to computer

from google.colab import files
files.download('processed_student_data.csv')